---
- name: Create a k8s namespace  
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: wikijs
        labels:
          name: wikijs

