---
- name: create infra  
  hosts: localhost  
  gather_facts: false  
  environment:    
    GOOGLE_CREDENTIALS: "{{ credentials_file }}"
  pre_tasks:
    - name: ansible-galaxy collection install google.cloud
      shell: ansible-galaxy collection install google.cloud
    - name: snap install google-cloud-sdk --classic
      shell: snap install google-cloud-sdk --classic
    - name: apt install npm 
      shell: apt install npm 
    - name: ansible-galaxy collection install community.kubernetes
      shell: ansible-galaxy collection install community.kubernetes
    - name: apt install python3-pip
      shell: apt install python3-pip
    - name: pip install requests
      shell: pip install requests
    - name: ansible-galaxy collection install cloud.common
      shell: ansible-galaxy collection install cloud.common
    - name: pip install kubernetes
      shell: pip install kubernetes
    - name: ansible-galaxy collection install community.kubernetes
      shell: ansible-galaxy collection install community.kubernetes
    - name: snap install kubectl --classic
      shell: snap install kubectl --classic

  roles:    
    - network    
    - k8s
    - wiki-js-deployment    
    - database-deployment
