---
- name: create infra  
  hosts: localhost  
  gather_facts: false  
  environment:    
    GOOGLE_CREDENTIALS: "{{ credentials_file }}"

  roles:    
    - network    
    - k8s
    - wiki-js-deployment    
    - database-deployment