---
- name: deploy multilevel application (wikijs and postgress database) on kubernetes cluster  
  hosts: localhost  
  gather_facts: true # é necessário recolher dados sobre o host para poder saber quais os comandos a executar (em que sistema operativo)
  environment:    
    GOOGLE_CREDENTIALS: "{{ credentials_file }}"
  pre_tasks:
    - name: instalation ansible utility on ubuntu host
      shell: "{{ item }}"
      loop:
        - ansible-galaxy collection install google.cloud 
        - ansible-galaxy collection install community.kubernetes
        - ansible-galaxy collection install cloud.common
        - snap install google-cloud-sdk --classic
        - apt install npm 
        - apt install python3-pip
        - pip install requests
        - pip install kubernetes
        - snap install kubectl --classic
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - name: instalation ansible utility on macOS host
      shell: "{{ item }}"
      loop:
        - brew install --cask google-cloud-sdk
      when: ansible_distribution == 'MacOSX'

  roles:    
    - requirements
    - network-cluster   
    - kubernets-cluster
    - postgres-database
    - wikijs-application    
    - prometheus-monitoring
    
