---
- name: create infra  
  hosts: localhost  
  gather_facts: false  
  environment:    
    GOOGLE_CREDENTIALS: "{{ credentials_file }}"

  roles:    
    - 


# destruir cluster e os recursos associados
# disable APIs
# guardar estado database?
    