---
- name: Create the Secrets file
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: postgres-secret
        namespace: wikijs
      type: Opaque
      data:
        ROOT: cm9vdA==
        ROOT_PASSWORD: U3Ryb25nUm9vdFBhc3N3b3Jk
        DATABASE: d2lraWpz
        USER: d2lraWpz
        PASSWORD: U3Ryb25nVXNlclBhc3N3b3Jk


- name: Create the Database Pod for wiki.js
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: postgres
        namespace: wikijs
      spec:
        selector:
          app: postgres
        ports:
        - name: postgres
          protocol: TCP
          port: 3306


- name: Deploy the Database
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: postgres
        namespace: wikijs
        labels:
          app: postgres
      spec:
        selector:
          matchLabels:
            app: postgres
        template:
          metadata:
            labels:
              app: postgres
          spec:
            containers:
            - name: postgres
              image: gcr.io/kubernets-cluster-335010/postgres
              command: [ "/bin/bash", "-c", "--" ]
              args: [ "while true; do sleep 30; done;" ]
              env:
              - name: MYSQL_ROOT_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgres-secret
                    key: ROOT_PASSWORD
              - name: MYSQL_DATABASE
                valueFrom:
                  secretKeyRef:
                    name: postgres-secret
                    key: DATABASE
              - name: MYSQL_USER
                valueFrom:
                  secretKeyRef:
                    name: postgres-secret
                    key: USER
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgres-secret
                    key: PASSWORD
              ports:
              - containerPort: 3306
                name: mysql
       


- name: Deploy the Wiki.js Service as NodePort
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "wikijs"
        namespace: wikijs
      spec:
        type: NodePort
        ports:
          - name: http
            port: 3000
        selector:
          app: "wikijs"


- name: Deploy the Wiki.js aplication
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: wikijs
        namespace: wikijs
        labels:
          app: wikijs
      spec:
        selector:
          matchLabels:
            app: wikijs
        template:
          metadata:
            labels:
              app: wikijs
          spec:
            containers:
            - name: wikijs
              image: gcr.io/kubernets-cluster-335010/requarks/wiki
              imagePullPolicy: Always
              command: [ "/bin/bash", "-c", "--" ]
              args: [ "while true; do sleep 30; done;" ]
              env:
              - name: DB_TYPE
                value: "postgres"
              - name: DB_HOST
                value: "postgres"
              - name: DB_PORT
                value: "3306"
              - name: DB_NAME
                valueFrom:
                  secretKeyRef:
                    name: postgres-secret
                    key: DATABASE
              - name: DB_USER
                valueFrom:
                  secretKeyRef:
                    name: postgres-secret
                    key: USER
              - name: DB_PASS
                valueFrom:
                  secretKeyRef:
                    name: postgres-secret
                    key: PASSWORD
              ports:
              - containerPort: 3000
                name: http

